# Outputs - Valores importantes después del despliegue

# URL pública del Application Load Balancer
output "alb_dns_name" {
  description = "El DNS público del Application Load Balancer."
  value       = aws_lb.main.dns_name
}

# Endpoint de RDS PostgreSQL (usar en DATABASE_URL del backend)
output "rds_endpoint" {
  description = "El endpoint de la base de datos RDS."
  value       = aws_db_instance.main.endpoint
}

# URL del repositorio ECR para docker push
output "ecr_repository_url" {
  description = "La URL del repositorio ECR para subir imágenes Docker."
  value       = aws_ecr_repository.main.repository_url
}

# IP pública de EC2 frontend (ssh -i clave.pem ec2-user@<IP>)
output "ec2_front_public_ip" {
  description = "IP pública de la instancia EC2 frontend (para SSH)."
  value       = aws_instance.front.public_ip
}

# IP pública de EC2 backend (ssh -i clave.pem ec2-user@<IP>)
output "ec2_back_public_ip" {
  description = "IP pública de la instancia EC2 backend (para SSH)."
  value       = aws_instance.back.public_ip
}

# Clave privada SSH (SENSIBLE - guardar: terraform output -raw ec2_private_key_pem > clave.pem)
output "ec2_private_key_pem" {
  description = "Private key PEM generated by Terraform (only set if Terraform created the key pair)."
  value       = length(tls_private_key.generated) > 0 ? tls_private_key.generated[0].private_key_pem : ""
  sensitive   = true
}

# ===============================================
# PRÁCTICA 5: Outputs para Elastic IPs y Route 53
# ===============================================

# Elastic IP del Frontend (IP estática)
output "frontend_elastic_ip" {
  description = "Elastic IP estática asignada al Frontend"
  value       = aws_eip.frontend.public_ip
}

# Elastic IP del Backend (IP estática)
output "backend_elastic_ip" {
  description = "Elastic IP estática asignada al Backend"
  value       = aws_eip.backend.public_ip
}

# Nameservers de Route 53 (COPIAR a Namecheap)
output "route53_nameservers" {
  description = "Nameservers de Route 53 - Configurar en Namecheap para delegar DNS"
  value       = aws_route53_zone.main.name_servers
}

# URL del dominio (Frontend)
output "domain_url" {
  description = "URL del dominio principal (Frontend)"
  value       = "http://${var.domain_name}"
}

# URL del API (Backend)
output "api_url" {
  description = "URL del subdominio API (Backend)"
  value       = "http://api.${var.domain_name}"
}